
import ReactQueryProvider from "@/util/ReactQueryProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <nav>
            <ul>
              <li><Link href={"/"}>home</Link></li>
              <li><Link href={"/about"}>about</Link></li>
              <li><Link href={"/todos"}>todo</Link></li>
            </ul>
          </nav>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
